# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [1]:
# ! pip install matplotlib
# ! pip install pandas
# ! pip install numpy

In [2]:
import math
import sys

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [4]:
# YOUR CHANGES HERE
q1a = np.array([0.0, 0.3, 0.65])
q1b = np.array([2.2, 6.2, 0.35])

p1 = q1a + q1b

In [5]:
p1

array([2.2, 6.5, 1. ])

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [6]:
# YOUR CHANGES HERE

p2 = math.sqrt(1**2 + 3**2 + 6**2)

In [7]:
p2

6.782329983125268

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [8]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [9]:
# YOUR CHANGES HERE

# reference: https://medium.com/@heyamit10/numpy-norm-fdc8dc604183

# q3_manual = math.sqrt(5.2**2 + 5.9**2 + 9.1**2 + 4.3**2 + 2.9**2)
# print(q3_manual)

p3 = np.linalg.norm(q3)

In [10]:
p3

np.float64(13.098091464026353)

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [11]:
# YOUR CHANGES HERE
# reference: https://numpy.org/doc/stable/reference/generated/numpy.dot.html
q4a = [2,0,3]
q4b = [0,4,1]

# visually can see it should be 3 since there are 2 numbers multiplied by 0
q4_manual = (2*0) + (0*4) + (3*1)
# print(q4_manual)

p4 = np.dot(q4a, q4b)

In [12]:
p4

np.int64(3)

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [13]:
# DO NOT CHANGE

u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [14]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [15]:
# YOUR CHANGES HERE
# reminder element wise multiplication of vectors returns a vector
p5 = u5 * v5

In [16]:
p5

array([ 5, 30, 10])

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [17]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [18]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [19]:
# YOUR CHANGES HERE

p6 = np.dot(u6, v6)

In [20]:
p6

np.float64(18.683400000000002)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [21]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [22]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [23]:
# YOUR CHANGES HERE
# reference: https://www.geeksforgeeks.org/python/how-to-calculate-cosine-similarity-in-python/
from numpy.linalg import norm
p7 = np.dot(u7, v7) / (norm(u7) * norm(v7))

In [24]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [25]:
# YOUR CHANGES HERE
# reference: 9.1 Lesson: Vector Notation and Basic Concepts Polar Coordinates for Direction and Magnitude,  section: Polar Coordinates for Direction and Magnitude
# per the lesson x = r * cos of the angle and y = r * sin of the angle

q7_angle = 1
q7_mag = 1

q7_x = q7_mag * math.cos(q7_angle)
q7_y = q7_mag * math.sin(q7_angle)

p8 = [q7_x, q7_y]

In [26]:
p8

[0.5403023058681398, 0.8414709848078965]

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [27]:
# YOUR CHANGES HERE
q9_scalar = 3.1
q9_vector = np.array([1.31, 2.06, 9.56, 1.79])

p9 = q9_scalar * q9_vector

In [28]:
p9

array([ 4.061,  6.386, 29.636,  5.549])

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [29]:
# YOUR CHANGES HERE
# reference: 9.1 Lesson: Vector Notation and Basic Concepts, Splitting Vectors Into Magnitudes and Directions

# find the magnitude, then divide everything by the magnitude

# start by finding the magnitude of the original matrix: 2.32520966796545
q10a_mag = math.sqrt(1.31**2 + 2.13**2 + -0.92**2)
# print(q10a_mag)

# divide by the magnitude
p10 = np.array([1.31/q10a_mag, 2.13/q10a_mag, -0.92/q10a_mag])

In [30]:
p10

array([ 0.56339005,  0.91604642, -0.39566324])

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [31]:
# reference: 9.6 Lesson: Orthogonality
# first check - are vectors all non-zero? yes
# now compute the dotproducts and see if they're 0

q11_target = np.array([1,0,0])

# [1,1,1] dot = 1
q11a = np.array([1,1,1])
q11a_dot = np.dot(q11_target, q11a)
# print(q11a_dot)

# [0.5,1,1] dot = 0.5
q11b = np.array([0.5,1,1])
q11b_dot = np.dot(q11_target, q11b)
# print(q11b_dot)

# [0,1,1] dot = 0
q11c = np.array([0,1,1])
q11c_dot = np.dot(q11_target, q11c)
print(q11c_dot)

p11 = np.array([0,1,1])

0


In [32]:
p11

array([0, 1, 1])

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [ ]:
# YOUR CHANGES HERE
# reference: 9.2 Lesson: Linear Dependence of Vectors
# reminder: A set of vectors v0, v1, etc. are linearly dependent if when multiplied by a coefficient and the products are added the result is a vector of 0's; at least one coefficient needs to be a non-0 number
        #   A vector is linearly dependent on previous ones if it adds no “new direction”
p12 = np.array([1,1,1])

In [34]:
p12

Ellipsis

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [65]:
# YOUR CHANGES HERE
# reference: 8.1 Lesson: Linear Algebra Preliminaries, What Is an Identity Matrix? 
# reference: https://numpy.org/doc/stable/reference/generated/numpy.identity.html
p13 = np.identity(3)

In [66]:
p13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [67]:
# YOUR CHANGES HERE
# break the problem donw
# x intercept will be where y = 0, so set y=0 in the equation and solve for x by doing c/a 

p14 = 2/5

In [68]:
p14

0.4

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [39]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [40]:
# YOUR CHANGES HERE
# similar to problem 7, solution was: p7 = np.dot(u7, v7) / (norm(u7) * norm(v7))

# set the array variables
q15_target = np.array([0.1, 0.5, 0.2])
q15_cat = q15["cat"]
q15_dog = q15["dog"]
q15_elephant = q15["elephant"]
q15_giraffe = q15["giraffe"]
q15_lion = q15["lion"]

# find the cosine similarities: Cat: 0.9960065188076062 Dog: 0.9666666666666665 Elephant: 0.5034965460952284 Giraffe: 0.32225169331774467 Lion: 0.9938079899999066
q15_catcosim = np.dot(q15_target, q15_cat) / (norm(q15_target) * norm(q15_cat))
q15_dogcosim = np.dot(q15_target, q15_dog) / (norm(q15_target) * norm(q15_dog))
q15_elephantcosim = np.dot(q15_target, q15_elephant) / (norm(q15_target) * norm(q15_elephant))
q15_giraffecosim = np.dot(q15_target, q15_giraffe) / (norm(q15_target) * norm(q15_giraffe))
q15_lioncosim = np.dot(q15_target, q15_lion) / (norm(q15_target) * norm(q15_lion))
print("Cat:", q15_catcosim, "Dog:", q15_dogcosim, "Elephant:", q15_elephantcosim, "Giraffe:", q15_giraffecosim, "Lion:", q15_lioncosim)

p15 = "cat"

Cat: 0.9960065188076062 Dog: 0.9666666666666665 Elephant: 0.5034965460952284 Giraffe: 0.32225169331774467 Lion: 0.9938079899999066


In [41]:
p15

'cat'

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [ ]:
# YOUR CHANGES HERE
# reference: 9.6 Lesson: Orthogonality, Definition: orthonormal vectors
# Orthonormal vectors: Orthogonal vectors with a magnitude of 1

p16a = ...

In [43]:
p16a

Ellipsis

In [44]:
# YOUR CHANGES HERE

p16b = ...

In [45]:
p16b

Ellipsis

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [46]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [47]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [48]:
# YOUR CHANGES HERE
# reference: https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

p17 = np.matmul(x17, y17)

In [49]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [50]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [51]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [52]:
# YOUR CHANGES HERE

p18 = ...

In [53]:
p18

Ellipsis

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [54]:
# YOUR CHANGES HERE
q19a = math.sqrt(0.1**2 + 0.3**2 + 0.9**2 + (-0.8)**2)
q19b = math.sqrt(0.2**2 + 0.2**2 + 0.7**2 + 0.6**2)
q19c = math.sqrt((-0.2)**2 + 0.2**2 + 0.7**2 + (-0.6)**2)
q19d = math.sqrt(1.0**2 + 1.0**2 + 0.4**2 + 0.5**2)

print("A:",q19a, "B:", q19b, "C:", q19c, "D:", q19d)
# Re-attempt: A: 1.2449899597988734 B: 0.9643650760992954 C: 0.9643650760992954 D: 1.5524174696260025
# Attempt 1 (had a few errors in the magnitudes) A: 0.5196152422706631 B: 0.9643650760992954 C: 0.36055512754639885 D: 1.6309506430300091

p19 = np.array([1.0, 1.0, 0.4, 0.5])

A: 1.2449899597988734 B: 0.9643650760992954 C: 0.9643650760992954 D: 1.5524174696260025


In [55]:
p19

array([1. , 1. , 0.4, 0.5])

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [56]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [57]:
# YOUR CHANGES HERE

p20 = 3 * x20 + 5

In [58]:
p20

array([5.6, 6.5, 4.1, 7.4])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR ANSWER HERE